export const router = {
  home: "/",
  send: "/send",
  signUp: "/sign-up",
  receive: "/receive",
  activity: "/activity",
  addAddress: "/add-address",
  addressBook: "/address-book",
  importPhase: "/import-phase",
  welcomeBack: "/welcome-back",
  importAccount: "/import-account",
  encodeAccount: "/encode-account",
  setupComplete: "/setup-complete",
  autoLockTimer: "/autoLock-Timer",
  createAccount: "/create-account",
  removeAccount: "/remove-account",
  backupAccount: "/backup-account",
  requestToSign: "/request-to-sign",
  chainActivity: "/chain-activity",
  createPassword: "/create-password",
  connectedSites: "/connected-sites",
  changePassword: "/change-password",
  tokenDashboard: "/token-dashboard",
  addRemoveToken: "/add-remove-token",
  requestToConnect: "/request-to-connect",
  requestToSignRaw: "/request-to-sign-raw",
  addImportForBoardedUser: "/add-import-for-boarded-user",
};
